name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# --- ADD THIS SECTION ---
permissions:
  contents: write # Allows the workflow to write to the repository content (e.g., gh-pages branch)
  pages: write    # Grants permission to deploy to GitHub Pages
  id-token: write # Required for securely deploying to GitHub Pages using OIDC
# ------------------------

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          # --- CHANGE THIS LINE ---
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub Actions token
          # ------------------------
          publish_dir: ./build
