name: Update News
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run news update script
        run: |
          # Replace this with your actual news update logic
          echo "News updated $(date)" > news.log

      - name: Commit and push changes if any
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-update news"
            git push
          else
            echo "No changes to commit"
          fi
