name: Update Content
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update news and scores
        run: |
          echo "Updating content..."
          # Add your update scripts here
          date > last-updated.txt
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@noreply.github.com"
          git add .
          git commit -m "Auto-content update"
          git push
